### ISSUE TITLE
fast_sample for dbf files?

### ISSUE THREAD

**Issue by joelgombin** [earino/fast_sample#1]
I'd love to see a tool similar to fast_sample for dbf files. There are several issues, I think:
- I think several dbf format specs coexist
- I guess one could use a tool such as [this one](http://manpages.ubuntu.com/manpages/gutsy/man1/dbfdump.1.html), but it kind of loses the interest of fast_sample which is to avoid havng to handle the whole file. 

What do you think? 

Example of a DBF file: the French national statistics institute, the INSEE, loves DBF files. E.g.: http://telechargement.insee.fr/fichiersdetail/rp19682011/dbase/rp19682011_individus_dbase.zip (38+ million rows).

**Comment by earino** [comment]
Would it be ok to input DBF files and output CSV files? For example

```
./fast_sample -p .01 input.dbf > sampled.csv
```

**Comment by joelgombin** [comment]
not only OK but great! (let's get rid of nasty dbf files as soon as we can...)

**Comment by earino** [comment]
Ok, support added! In order for it to work, you will need a few Perl modules installed (Text::CSV and XBase), but I think you will find the performance pretty acceptable (check out the DBF performance information in the README!)

**Comment by joelgombin** [comment]
Wow, that's pretty awesome! Thanks a lot!
